#!/usr/bin/env python3
"""Derive the human-readable membraneome workbook FROM the CSV source of record.

    python scripts/build_membraneome_xlsx.py \
        --csv data/census/membraneome-reconstructed-2026-08-04.csv \
        --out data/census/membraneome-reconstructed-2026-08-04.xlsx

⚠ WHY THIS SCRIPT EXISTS AT ALL. The CSV and the workbook held the same 7,903 rows,
built side by side from the same upstream scrape. **That is two paths to one
quantity with nothing comparing them** — the signature defect class of this
project — and they would have diverged the first time someone regenerated either
one. This script makes them **parent and child**: the CSV is the source of record
(RULINGS-2026-08-04-F016 §4), the workbook is derived, and there is exactly one
derivation. `tests/test_membraneome_artifacts.py` reddens if they disagree.

⚠ PROVENANCE IS BOUND, NOT ADJACENT. The workbook records the **sha256 of the CSV
it was actually built from**, so a workbook can always be traced to its parent
rather than to a filename that two different files could answer to.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import sys
from collections import Counter
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

# Columns this project adds on top of the nine scraped from the source table.
DERIVED_COLUMNS = [
    "surfy_class",
    "uniprot_status",
    "uniprot_current_accession",
    "uniprot_current_entry_name",
    "uniprot_primary_gene",
    "gene_symbol_changed",
    "foldable",
    "class_conflict",
]


def provenance(csv_name: str, csv_sha256: str, counts: Counter, distinct: dict) -> list[str]:
    return [
        "WHAT THIS FILE IS",
        "The full human membraneome table (SURFY / Bausch-Fluck et al. 2018 PNAS Table S3),",
        "annotated against the UniProt reviewed human proteome retrieved 2026-08-04 and conformed",
        "to RULINGS-2026-08-04-F016. See F-016 in docs/README.md.",
        "",
        "THIS WORKBOOK IS DERIVED, NOT AUTHORED (rulings: one source, one derivation)",
        f"  parent : {csv_name}",
        f"  sha256 : {csv_sha256}",
        "  built by: scripts/build_membraneome_xlsx.py",
        "  The CSV is the machine-readable source of record - diffable, greppable, reviewable in a",
        "  PR. Tests read the CSV. This workbook is the human-readable copy of those same rows.",
        "  Do not edit this file: edit the CSV and rebuild, or the two will drift.",
        "",
        "WHAT IT IS NOT",
        "NOT the upstream table_S3_surfaceome.xlsx. That file has never been obtained; the published",
        "URL serves a 132-byte Git LFS pointer stub, sha256",
        "f3df0fa89f4a6b16b7fb6afa95732e0b7a3391579c1864c2d180f02a13aafc80. Named so it cannot be",
        "mistaken for the source artifact.",
        "",
        "DENOMINATORS ALWAYS STATE THEIR KEY",
        f"  surface:      {counts['surface']:,} identifiers  ·  {distinct['surface']:,} distinct accessions   <- the denominator",
        f"  non_surface:  {counts['non_surface']:,} identifiers  ·  {distinct['non_surface']:,} distinct accessions",
        f"  unclassified: {counts['unclassified']:,} identifiers  ·  {distinct['unclassified']:,} distinct accessions",
        f"  total:        {sum(counts.values()):,} identifiers  ·  {distinct['ALL']:,} distinct accessions",
        "",
        "THREE CLASSES, NEVER TWO",
        "  Derive from surfy_class, NEVER from row position. The scrape stacked a 2,886-row surface",
        "  extract above a 'Non_Surface' marker with the FULL table below it; the marker is a section",
        "  heading, not a partition. unclassified is never merged into either class and never dropped.",
        "  'Not positive' is not negative: the complement (5,017) overstates the negative class by 126%.",
        "",
        "BUCKETS",
        "  merged   -- the pre-merge identifier is KEPT in 'UniProt Accession' and never overwritten.",
        "              'How many arrived through a merge?' stays answerable.",
        "  inactive -- foldable=no (no current sequence). Retained and flagged. Never dropped.",
        "  class_conflict -- accessions carrying rows in more than one class. The classifier did NOT",
        "              contradict itself: each conflicting pair carries distinct pre-merge accessions",
        "              and exactly one row per pair is merged. UniProt's merge manufactured the",
        "              contradiction. Resolved by NEITHER - resolving would assert that a merged",
        "              entity has one localization, a claim nobody has made.",
        "",
        "CAVEAT",
        "  The per-cell values of the non-surface rows cannot be validated against a source that was",
        "  never served. Corroboration reaches the counts and the surface membership, no further.",
        "  If the upstream xlsx is obtained (LFS pointer declares size 6864772, oid 2f1b8262...), it",
        "  supersedes this file without argument.",
    ]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", required=True, help="the CSV source of record (parent)")
    ap.add_argument("--out", required=True, help="workbook to write (child)")
    args = ap.parse_args(argv)

    csv_path, out_path = Path(args.csv), Path(args.out)
    if not csv_path.exists():
        raise SystemExit(f"MISSING PARENT: {csv_path}\n  The workbook is derived from the CSV; "
                         f"there is no other path to it.")

    raw = csv_path.read_bytes()
    csv_sha256 = hashlib.sha256(raw).hexdigest()

    with open(csv_path, newline="", encoding="utf-8") as fh:
        rd = csv.reader(fh)
        header = next(rd)
        body = [row for row in rd]

    missing = [c for c in DERIVED_COLUMNS if c not in header]
    if missing:
        raise SystemExit(f"PARENT IS MISSING DERIVED COLUMNS: {missing}")

    ci = {c: header.index(c) for c in header}
    counts = Counter(r[ci["surfy_class"]] for r in body)
    distinct = {k: len({r[ci["uniprot_current_accession"]] for r in body
                        if r[ci["surfy_class"]] == k})
                for k in ("surface", "non_surface", "unclassified")}
    distinct["ALL"] = len({r[ci["uniprot_current_accession"]] for r in body})

    wb = Workbook()
    sh = wb.active
    sh.title = "membraneome"
    sh.append(header)
    for c in sh[1]:
        c.font = Font(bold=True)
    sh.freeze_panes = "A2"
    for row in body:
        sh.append(row)

    prov = wb.create_sheet("PROVENANCE")
    prov.column_dimensions["A"].width = 118
    for line in provenance(csv_path.name, csv_sha256, counts, distinct):
        prov.append([line])

    wb.save(out_path)
    print(f"parent {csv_path} sha256={csv_sha256}", file=sys.stderr)
    print(f"wrote  {out_path}  ({len(body)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
